displayName=Ultimate Task Master
author=FattestCat
support=https://github.com/FattestCat/Ultimate-Task-Master
description=Track and manage in-game tasks and goals
tags=tasks,goals,tracker,task-master
plugins=com.ultimatetaskmaster.UltimateTaskMasterPlugin
